# Generated by Django 2.2.3 on 2019-07-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('alternate_email', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=15)),
                ('alternate_mobile', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=60)),
                ('hobbies', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
